"""Geo utilities. Real GPS coordinates would come from bin-mounted GPS/IoT
modules or the collection vehicle's telematics in a production deployment;
here they are generated by data_science/simulate_sensors.py and stored on
the Location model.
"""
from __future__ import annotations

import math

EARTH_RADIUS_KM = 6371.0088


def haversine_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Great-circle distance between two lat/lon points, in kilometres."""
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)

    a = (
        math.sin(dphi / 2) ** 2
        + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2) ** 2
    )
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    return EARTH_RADIUS_KM * c


def travel_minutes(distance_km: float, speed_kmph: float) -> float:
    if speed_kmph <= 0:
        return float("inf")
    return (distance_km / speed_kmph) * 60.0
