import datetime as dt
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import pandas as pd
import plotly.express as px
import streamlit as st

from database.db import get_session
from database.models import BinSensorReading, CollectionRecord
from frontend.components.common import badge, inject_style, require_login
from services.bin_service import bin_history, get_bin, list_bins, refresh_bin_statuses

user = require_login()
inject_style()
st.title("Smart Bin Monitoring")
st.caption("Bin ID, location, waste type, fill level, history and status.")
st.markdown(badge("simulated") + " sensor data for this prototype.", unsafe_allow_html=True)

with get_session() as session:
    refresh_bin_statuses(session)
    bins = list_bins(session)

if not bins:
    st.info("No bins found. Run `python -m database.init_db` to seed demo data.")
    st.stop()

df = pd.DataFrame([
    {
        "Bin Code": b.bin_code, "Location": b.location.name, "Type": b.location.location_type,
        "Category": b.waste_category.label, "Fill %": round(b.current_fill_level, 1),
        "Status": b.status.replace("_", " ").title(),
        "Last Collection": b.last_collection_time.strftime("%Y-%m-%d %H:%M") if b.last_collection_time else "Not observed",
    }
    for b in bins
])

f1, f2, f3 = st.columns(3)
status_filter = f1.multiselect("Filter by status", sorted(df["Status"].unique()))
category_filter = f2.multiselect("Filter by category", sorted(df["Category"].unique()))
search = f3.text_input("Search location")

filtered = df.copy()
if status_filter:
    filtered = filtered[filtered["Status"].isin(status_filter)]
if category_filter:
    filtered = filtered[filtered["Category"].isin(category_filter)]
if search:
    filtered = filtered[filtered["Location"].str.contains(search, case=False)]

st.dataframe(filtered, use_container_width=True, hide_index=True)

st.divider()
st.subheader("Bin Detail")
selected_code = st.selectbox("Select a bin", [b.bin_code for b in bins])
bin_obj = next(b for b in bins if b.bin_code == selected_code)

with get_session() as session:
    history = bin_history(session, bin_obj.id, limit=300)

m1, m2, m3, m4 = st.columns(4)
m1.metric("Current Fill", f"{bin_obj.current_fill_level:.0f}%")
m2.metric("Status", bin_obj.status.replace("_", " ").title())
m3.metric("Capacity", f"{bin_obj.capacity_liters:.0f} L")
m4.metric("Last Collection", bin_obj.last_collection_time.strftime("%b %d, %H:%M") if bin_obj.last_collection_time else "Not observed")

if history:
    hist_df = pd.DataFrame({"timestamp": [h.timestamp for h in history], "fill_level": [h.fill_level for h in history]})
    fig = px.line(hist_df, x="timestamp", y="fill_level", labels={"fill_level": "Fill %"}, title=f"{selected_code} — fill level history")
    fig.add_hline(y=90, line_dash="dot", line_color="#c62828", annotation_text="critical")
    st.plotly_chart(fig, use_container_width=True)
    st.caption(badge("simulated") + " Historical readings are generated by data_science/simulate_sensors.py in this prototype.", unsafe_allow_html=True)
else:
    st.info("No sensor history for this bin yet. Run `python -m data_science.simulate_sensors`.")

if user["role"] in ("operator", "admin"):
    st.divider()
    if st.button(f"✅ Mark {selected_code} as Collected Now", type="primary"):
        with get_session() as session:
            b = get_bin(session, bin_obj.id)
            now = dt.datetime.utcnow()
            session.add(CollectionRecord(
                bin_id=b.id, operator_id=user["id"], scheduled_time=now, collected_time=now,
                status="completed", fill_level_at_collection=b.current_fill_level,
            ))
            session.add(BinSensorReading(bin_id=b.id, timestamp=now, fill_level=2.0, is_simulated=False))
            b.current_fill_level = 2.0
            b.last_collection_time = now
            b.status = "normal"
        st.success(f"{selected_code} marked collected by {user['full_name']} (verified, real action).")
        st.rerun()
